services:
  core:
    volumes:
      - ./core/src:/app/src
      - ./core/deno.json:/app/deno.json
    command: ["deno", "run", "--watch", "--allow-net", "--allow-env", "--allow-read", "src/main.ts"]
